#####
# This image builds upon php-base
# Here we are going to add gbmcarlos/php-runtime's PHP Runtime Interface Client
#####

FROM gbmcarlos/php-base as base

COPY --from=gbmcarlos/php-runtime /opt /opt
